name: Module Submission
description: Preferred Magisk Module submission template
title: '[Module] module_id'
body:
  - type: markdown
    attributes:
      value: |
        ## Please read
        
        You should read our [General Guidelines](https://github.com/Magisk-Modules-Alt-Repo/submission#general-guidelines) and [Source Code Guidelines](https://github.com/Magisk-Modules-Alt-Repo/submission#source-code-guidelines) before you submit your module 

        > If your module includes non-free dependencies or something else, please check [Anti-Features](https://github.com/Magisk-Modules-Alt-Repo/submission#anti-features) before you submit your module

        **Quick guidelines:**
        - ID must match the id in module.prop
        - Title must include the module id — like `[Module] example_module`. The bot will reject the module when not
        - Once approved, your module will be added to our repo as https://github.com/Magisk-Modules-Alt-Repo/example_module
        
  - type: input
    id: module-id
    attributes:
      label: ID
      placeholder: example_module
    validations:
      required: true
  - type: input
    id: module-name
    attributes:
      label: Name
      placeholder: Example Module
    validations:
      required: true
  - type: textarea
    id: module-description
    attributes:
      label: Description
      placeholder: A simple module that does this, that, and the other thing.
    validations:
      required: true
  - type: input
    id: module-link
    attributes:
      label: Module repository link
      placeholder: https://www.github.com/username/repo
    validations:
      required: true
  - type: input
    id: module-source-code
    attributes:
      label: Source code link (for compiled binaries/APKs)
      placeholder: https://www.github.com/username/repo
  - type: dropdown
    id: antifeatures
    attributes:
      label: Anti-Features
      description: Only apply if your module has one of these
      multiple: true
      options:
        - Advertising (Ads)
        - Known Vulnerability (KnownVuln)
        - NSFW (NSFW)
        - No Source Since (NoSourceSince)
        - Non-Free Addons (NonFreeAdd)
        - Non-Free Assets (NonFreeAssets)
        - Non-Free Dependencies (NonFreeDep)
        - NonFreeNet (NonFreeNet)
        - Tracking (Tracking)
        - Upstream Non-Free(UpstreamNonFree)
        - Obfuscation (Obfuscation)
        - Unasked removal (UnaskedRemoval)
